messages,
    tasks,
    habits,
    okrs,
    events,
    lists,
    categories,
    collaborators,
    friends,
    colorSettings,
    searchTerm,
    setSearchTerm,
    selectedCategories,
    setSelectedCategories,
    priorityRange,
    setPriorityRange,
    markMessagesAsRead,
    addTask,
    updateTask,
    deleteTask,
    toggleBookmark,
    toggleComplete,
    addHabit,
    updateHabit,
    deleteHabit,
    toggleHabitCompletion,
    addOKR,
    updateOKR,
    deleteOKR,
    addEvent,
    updateEvent,
    deleteEvent,
    addList,
    updateList,
    deleteList,
    addCategory,
    updateCategory,
    deleteCategory,
    sendFriendRequest,
    login: async () => {},
    register: async () => {},
    loginWithGoogle: async () => {},
    logout: async () => {},
  };
